version: "3.9"

services:
  web:
    build: .
    expose: 
      - 443
    ports:
      - "443:443"
    volumes: 
      - /home/ubuntu/certs:/certs
    command: "gunicorn -w 4 --threads 12 -b :443 --certfile /certs/fullchain.pem --keyfile /certs/privkey.pem 'main:app'"
